config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/help", to: "static_pages#help"
  get "/signup", to: "users#new"
  root "static_pages#home"
  get  "/signup",  to: "users#new"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :words , only: [:index]
  resources :categories, only: [:index, :show] do
    resources :lessons, only: [:create]
  end
  resources :lessons
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if current_user.present?
      @activities = Activity.activities_by(current_user.id).order_by_activity
        .paginate page: params[:page], per_page: Settings.per_pages
    end
  end

  def help
  end
end

app/views/static_pages/_home_private.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="user_info">
      <h1>
        <%= gravatar_for current_user %>
        <%= current_user.name %>
      </h1>
    </div>
    <br><br>
    <%= render "shared/stats" %>
    <br/><br/>
    <div>
      <%= link_to t("listword"), words_path,
      class: "btn btn-info btn-block" %>
    </div>
    <br>
    <div>
      <%= link_to t("startlesson"), categories_path,
      class: "btn btn-primary btn-block" %>
    </div>
  </div>
  <div class="col-md-8 col-offset-2 panel-activity">
    <div class="panel panel-default">
      <div class="panel-heading text-center">Activity
        <%= link_to current_user.name, current_user %>
      </div>
      <div class="panel-body"><p>
        <%= render "shared/activities", activities: @activities %>
      </p>
    </div>
    <div class="text-center">
      <%= will_paginate @activities %>
    </div>
  </div>
</div>
</div>

app/views/static_pages/_home_public.html.erb
<center>
  <div class="center jumbotron">
    <marquee><h2><%= t "introduction" %></h2></marquee>
    <h3>
      <%= t "guide" %>
    </h3>
    <br>
    <%= link_to t("signup"), signup_path, class: "btn btn-lg btn-primary" %>
  </div>
</center>

app/views/static_pages/help.html.erb
<% provide :title, t("help") %>
<center><h1><%= t "help" %></h1></center>
<p><%= t "guide" %></p>

app/views/static_pages/home.html.erb
<% provide :title, t("home") %>
<%= render logged_in? ? "home_private" : "home_public"%>