config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/help", to: "static_pages#help"
  get "/signup", to: "users#new"
  root "static_pages#home"
  get  "/signup",  to: "users#new"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :words , only: [:index]
  resources :categories, only: [:index, :show] do
    resources :lessons, only: [:create]
  end
  resources :lessons
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons, dependent: :destroy
  has_many :words, dependent: :destroy
  validates :name, presence: true, length: {maximum: Settings.max_name_category},
    uniqueness: {case_sensitive: false}

  scope :order_by_category, -> {order(created_at: :desc)}

  def base_resource
    "#{self.name},#{category_path self}"
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :load_category, only: [:edit, :show, :update, :destroy]

  def index
    @categories = Category.order_by_category.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def destroy
    @category.destroy
    make_activity t("delete_category"),@category
    redirect_to admin_categories_path
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t"message.create_success"
      make_activity t("create_category"), @category
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "message.update_success"
      make_activity t("update_category"), @category
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  private
  def category_params
    params.require(:category).permit :name
  end

  def load_category
    @category = Category.find_by id: params[:id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_category, only: :show

  def index
    @categories = Category.order_by_category.paginate page: params[:id], per_page: Settings.per_pages
  end

  def show
    @lessons = @category.lessons.user_start(current_user).paginate page: params[:page],
      per_page: Settings.per_pages
  end

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category
    flash[:dranger] = t "notcagetory"
    redirect_to category_path
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<% provide :title, t("categories") %>
<center><h2><%= t "categories" %></h2></center>
<% @categories.each do |category|%>
  <div class="container-fluid bg-2 text-center">
    <h3 class="margin"><%= category.name %></h3>
    <p><%= t :description %></p>
    <%= link_to category, class: "btn btn-primary btn_start" do %>
      <span class="glyphicon glyphicon-play"></span>
      <%= t :start %>
    <% end %>
  </div>
<% end %>

app/views/categories/show.html.erb
<% provide :title, t("lessons") %>
<h2><%= @category.name %></h2>
<div class="row">
  <div class="col-md-12">
    <div class="pull-right">
      <%= link_to category_lessons_path(@category), method: :post,
        class: "btn btn-primary" do %>
        <span class="glyphicon glyphicon-play"></span> <%= t :start_new_lesson %>
      <% end %>
    </div>
  </div>
</div>
<hr/>
<h3><%= t :lessons %></h3>
<% if @lessons.any? %>
  <table class="table table-hover">
    <tr>
      <th><%= t :lesson %></th>
      <th><%= t :status %></th>
      <th></th>
    </tr>
    <%= render @lessons %>
  </table>
  <div class="text-center">
    <%= will_paginate @lessons %>
  </div>
<% else %>
  <%= t :no_items_found %>
<% end %>