config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/help", to: "static_pages#help"
  get "/signup", to: "users#new"
  root "static_pages#home"
  get  "/signup",  to: "users#new"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :words , only: [:index]
  resources :categories, only: [:index, :show] do
    resources :lessons, only: [:create]
  end
  resources :lessons
end

app/views/layouts/_footer.html.erb
<br/><br/>
<hr/>
<footer class="footer container">
  <div class="pull-left"> &copy;<%= t("name") %></div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle"
      data-toggle="collapse" data-target="#navbar-collapse"
      aria-expanded="false">
      <span class="sr-only"><%= t :toggle_navigation %></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <b><%= link_to t("logo"), root_path, class: "logo" %></b>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("home"), root_path %></li>
        <li><%= link_to t("help"), help_path %></li>
        <% if logged_in? %>
        <li><%= link_to t("users"), users_path if logged_in? %></li>
        <% if logged_in? && current_user.is_admin %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t :management %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("lesson"), "#" %></li>
              <li><%= link_to t("category"), "#" %></li>
            </ul>
          </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t "wellcome" %><%= current_user.name %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t("profile"), current_user %></li>
            <li><%= link_to t("setting"), "#" %></li>
            <li class="divider"></li>
            <li>
              <%= link_to t("logout"), logout_path, method: :delete %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to t("login"), login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
</head>
<body>
  <%=render "layouts/header"%>
  <div class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>